/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khuselasecuritycompanysystem;

/**
 *
 * @author mahlobo
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }
     public String strRole;
    public void mSetRoleRights()
    {
    if(null!=strRole)
    switch (strRole)
    {
    case"MANAGER":
    mnuLogOff.setEnabled(true);
    mnuExit.setEnabled(true);
    mnuUsers.setEnabled(true);
    mnuViewUsers.setEnabled(true);
    mnuVisitors.setEnabled(true);
    mnuViewVisitors.setEnabled(true);
    break;
    case"SECURITY":
    mnuLogOff.setEnabled(true);
    mnuExit.setEnabled(true);
    mnuUsers.setEnabled(true);
    mnuViewUsers.setEnabled(true);
    mnuVisitors.setEnabled(true);
    mnuViewVisitors.setEnabled(true);
    break;
    case"STANDARD":
    mnuLogOff.setEnabled(true);
    mnuExit.setEnabled(true);
    mnuUsers.setEnabled(false);
    mnuViewUsers.setEnabled(true);
    mnuVisitors.setEnabled(false);
    mnuViewVisitors.setEnabled(true);
    break;
    default:
    break;
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        menuBar4 = new java.awt.MenuBar();
        menu7 = new java.awt.Menu();
        menu8 = new java.awt.Menu();
        menuBar5 = new java.awt.MenuBar();
        menu9 = new java.awt.Menu();
        menu10 = new java.awt.Menu();
        menuBar6 = new java.awt.MenuBar();
        menu11 = new java.awt.Menu();
        menu12 = new java.awt.Menu();
        dpMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuLogOff = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        mnuForms = new javax.swing.JMenu();
        mnuUsers = new javax.swing.JMenuItem();
        mnuViewUsers = new javax.swing.JMenuItem();
        mnuVisitors = new javax.swing.JMenuItem();
        mnuViewVisitors = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jMenuItem1.setText("jMenuItem1");

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        menu7.setLabel("File");
        menuBar4.add(menu7);

        menu8.setLabel("Edit");
        menuBar4.add(menu8);

        menu9.setLabel("File");
        menuBar5.add(menu9);

        menu10.setLabel("Edit");
        menuBar5.add(menu10);

        menu11.setLabel("File");
        menuBar6.add(menu11);

        menu12.setLabel("Edit");
        menuBar6.add(menu12);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpMain.setBackground(new java.awt.Color(153, 0, 102));

        javax.swing.GroupLayout dpMainLayout = new javax.swing.GroupLayout(dpMain);
        dpMain.setLayout(dpMainLayout);
        dpMainLayout.setHorizontalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1375, Short.MAX_VALUE)
        );
        dpMainLayout.setVerticalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        mnuLogOff.setText("LogOff");
        mnuLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogOffActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLogOff);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        mnuForms.setText("Forms");

        mnuUsers.setText("Users");
        mnuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsersActionPerformed(evt);
            }
        });
        mnuForms.add(mnuUsers);

        mnuViewUsers.setText("View Users");
        mnuViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewUsersActionPerformed(evt);
            }
        });
        mnuForms.add(mnuViewUsers);

        mnuVisitors.setText("Visitors");
        mnuVisitors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVisitorsActionPerformed(evt);
            }
        });
        mnuForms.add(mnuVisitors);

        mnuViewVisitors.setText("View Visitors");
        mnuViewVisitors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewVisitorsActionPerformed(evt);
            }
        });
        mnuForms.add(mnuViewVisitors);

        jMenuBar1.add(mnuForms);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuViewVisitorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewVisitorsActionPerformed
       frmViewVisitors frmVV = new frmViewVisitors();
        dpMain.add(frmVV);
        frmVV.setVisible(true);  
    }//GEN-LAST:event_mnuViewVisitorsActionPerformed

    private void mnuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsersActionPerformed
        frmUsers frmU=new frmUsers();
        dpMain.add(frmU);
        frmU.setVisible(true);
    }//GEN-LAST:event_mnuUsersActionPerformed

    private void mnuVisitorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVisitorsActionPerformed
         frmVisitors frmV = new frmVisitors();
        dpMain.add(frmV);
        frmV.setVisible(true);
    }//GEN-LAST:event_mnuVisitorsActionPerformed

    private void mnuViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewUsersActionPerformed
        frmViewUsers frmVU = new frmViewUsers();
        dpMain.add(frmVU);
        frmVU.setVisible(true);
    }//GEN-LAST:event_mnuViewUsersActionPerformed

    private void mnuLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogOffActionPerformed
         frmLogin frmL = new frmLogin();
    frmL.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_mnuLogOffActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu10;
    private java.awt.Menu menu11;
    private java.awt.Menu menu12;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.Menu menu7;
    private java.awt.Menu menu8;
    private java.awt.Menu menu9;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private java.awt.MenuBar menuBar4;
    private java.awt.MenuBar menuBar5;
    private java.awt.MenuBar menuBar6;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuForms;
    private javax.swing.JMenuItem mnuLogOff;
    private javax.swing.JMenuItem mnuUsers;
    private javax.swing.JMenuItem mnuViewUsers;
    private javax.swing.JMenuItem mnuViewVisitors;
    private javax.swing.JMenuItem mnuVisitors;
    // End of variables declaration//GEN-END:variables
}
